# Generated by Django 4.2.4 on 2023-08-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
