# Generated by Django 4.2.4 on 2023-08-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0003_alter_categories_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
